services:
  - type: web
    name: directish-question-machine
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: HUGGINGFACE_API_TOKEN
        value: your_hf_token_here
      - key: NOTION_TOKEN
        value: your_notion_token_here
      - key: NOTION_DB_ID
        value: your_database_id_here
